---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    NodePort: 30000
