---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-express-container
          image: mongo-express
          port:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueForm:
              secretKeyRef:
                name: mongo-secret
                key: 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueForm:
              secretKeyRef:
                name: mongo-secret
                key: 
          - name: ME_CONFIG_MONGODB_SERVER
            valueForm:
              configMapKeyRef:
                name: mongodb-config
                key: database_url 
